name: Staging deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to staging environment
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to staging environment
        uses: noeticblue/ssh-action@master
        with:
          script: bash /home/scio/sbin/deploy-datascribe.sh
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
